const GROUPS = {
    "groups": {
        "0": "smileys_people",
        "1": "animals_nature",
        "2": "food_drink",
        "3": "travel_places",
        "4": "activities",
        "5": "objects",
        "6": "symbols",
        "7": "flags"
    },
    "subgroups": {
        "0": "face_positive",
        "1": "face_neutral",
        "2": "face_negative",
        "3": "face_sick",
        "4": "face_role",
        "5": "face_fantasy",
        "6": "cat_face",
        "7": "monkey_face",
        "8": "person",
        "9": "person_role",
        "10": "person_fantasy",
        "11": "person_gesture",
        "12": "person_activity",
        "13": "person_sport",
        "14": "family",
        "15": "body",
        "16": "emotion",
        "17": "clothing",
        "18": "animal_mammal",
        "19": "animal_bird",
        "20": "animal_amphibian",
        "21": "animal_reptile",
        "22": "animal_marine",
        "23": "animal_bug",
        "24": "plant_flower",
        "25": "plant_other",
        "26": "food_fruit",
        "27": "food_vegetable",
        "28": "food_prepared",
        "29": "food_asian",
        "30": "food_sweet",
        "31": "drink",
        "32": "dishware",
        "33": "place_map",
        "34": "place_geographic",
        "35": "place_building",
        "36": "place_religious",
        "37": "place_other",
        "38": "transport_ground",
        "39": "transport_water",
        "40": "transport_air",
        "41": "hotel",
        "42": "time",
        "43": "sky_weather",
        "44": "event",
        "45": "award_medal",
        "46": "sport",
        "47": "game",
        "48": "sound",
        "49": "music",
        "50": "musical_instrument",
        "51": "phone",
        "52": "computer",
        "53": "light_video",
        "54": "book_paper",
        "55": "money",
        "56": "mail",
        "57": "writing",
        "58": "office",
        "59": "lock",
        "60": "tool",
        "61": "medical",
        "62": "other_object",
        "63": "transport_sign",
        "64": "warning",
        "65": "arrow",
        "66": "religion",
        "67": "zodiac",
        "68": "av_symbol",
        "69": "other_symbol",
        "70": "keycap",
        "71": "alphanum",
        "72": "geometric",
        "73": "flag",
        "74": "country_flag",
        "75": "subdivision_flag"
    },
    "hierarchy": {
        "0": [
            0,
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17
        ],
        "1": [
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25
        ],
        "2": [
            26,
            27,
            28,
            29,
            30,
            31,
            32
        ],
        "3": [
            33,
            34,
            35,
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43
        ],
        "4": [
            44,
            45,
            46,
            47
        ],
        "5": [
            48,
            49,
            50,
            51,
            52,
            53,
            54,
            55,
            56,
            57,
            58,
            59,
            60,
            61,
            62
        ],
        "6": [
            63,
            64,
            65,
            66,
            67,
            68,
            69,
            70,
            71,
            72
        ],
        "7": [
            73,
            74,
            75
        ]
    }
};
export default GROUPS;